# Generated by Django 4.0 on 2021-12-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
